@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command
Class CommandResult
Class Model

Class AddressBookParser {
  +parseCommand(args): Command
}
Class ReminderCommand {
  +COMMAND_WORD: String
  +execute(Model): CommandResult
}

AddressBookParser ..> ReminderCommand : <<create>>
@enduml
