@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
  interface "Ui" as Ui
  abstract class "UiPart<T>" as UiPart
  class UiManager
  class MainWindow
  class HelpWindow
  class ResultDisplay
  class ApplicationListPanel
  class ApplicationCard
  class StatusBarFooter
  class CommandBox
  interface "CommandExecutor" as CommandExecutor <<functional interface>>
}

package Model <<Rectangle>> {
  class "Application" as Application MODEL_COLOR
}

package Logic <<Rectangle>> {
  interface "Logic" as Logic LOGIC_COLOR
}

class MainApp #FFFFFF

MainApp ..> Ui

UiManager ..|> Ui
UiManager *--> "1" MainWindow

MainWindow --> Logic
UiManager --> Logic

MainWindow --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ApplicationListPanel --|> UiPart
ApplicationCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

MainWindow *--> "1" CommandBox
MainWindow *--> "1" ResultDisplay
MainWindow *--> "1" ApplicationListPanel
MainWindow *--> "1" StatusBarFooter
MainWindow ..> HelpWindow

ApplicationListPanel *--> "*" ApplicationCard

ApplicationListPanel ..> Application
ApplicationCard ..> Application
CommandBox --> CommandExecutor

ApplicationListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
@enduml